// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: trivia.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TriviaService_GetQuestion_FullMethodName = "/trivia.TriviaService/GetQuestion"
)

// TriviaServiceClient is the client API for TriviaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TriviaServiceClient interface {
	GetQuestion(ctx context.Context, in *GetQuestionRequest, opts ...grpc.CallOption) (*Question, error)
}

type triviaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTriviaServiceClient(cc grpc.ClientConnInterface) TriviaServiceClient {
	return &triviaServiceClient{cc}
}

func (c *triviaServiceClient) GetQuestion(ctx context.Context, in *GetQuestionRequest, opts ...grpc.CallOption) (*Question, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Question)
	err := c.cc.Invoke(ctx, TriviaService_GetQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriviaServiceServer is the server API for TriviaService service.
// All implementations must embed UnimplementedTriviaServiceServer
// for forward compatibility.
type TriviaServiceServer interface {
	GetQuestion(context.Context, *GetQuestionRequest) (*Question, error)
	mustEmbedUnimplementedTriviaServiceServer()
}

// UnimplementedTriviaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTriviaServiceServer struct{}

func (UnimplementedTriviaServiceServer) GetQuestion(context.Context, *GetQuestionRequest) (*Question, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestion not implemented")
}
func (UnimplementedTriviaServiceServer) mustEmbedUnimplementedTriviaServiceServer() {}
func (UnimplementedTriviaServiceServer) testEmbeddedByValue()                       {}

// UnsafeTriviaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriviaServiceServer will
// result in compilation errors.
type UnsafeTriviaServiceServer interface {
	mustEmbedUnimplementedTriviaServiceServer()
}

func RegisterTriviaServiceServer(s grpc.ServiceRegistrar, srv TriviaServiceServer) {
	// If the following call pancis, it indicates UnimplementedTriviaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TriviaService_ServiceDesc, srv)
}

func _TriviaService_GetQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriviaServiceServer).GetQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriviaService_GetQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriviaServiceServer).GetQuestion(ctx, req.(*GetQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TriviaService_ServiceDesc is the grpc.ServiceDesc for TriviaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TriviaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trivia.TriviaService",
	HandlerType: (*TriviaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuestion",
			Handler:    _TriviaService_GetQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trivia.proto",
}
