version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  postgresdb:
    image: postgres:14
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_databases:/docker-entrypoint-initdb.d
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # graphql:
  #   build:
  #     context: ./graphql
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./graphql:/app
  #     - /app/build
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   environment:
  #     LOBBY_GRPC_PORT: ${LOBBY_GRPC_PORT}
  #     PORT: 3000

  lobby:
    build:
      context: ./services/lobby
      dockerfile: Dockerfile.dev
    ports:
      - "${LOBBY_GRPC_PORT}:${LOBBY_GRPC_PORT}"
    networks:
      - app-network
    volumes:
      - ./services/lobby:/app
      - /app/bin
    depends_on:
      - mongodb
    environment:
      GRPC_PORT: ${LOBBY_GRPC_PORT}

volumes:
  postgres_data:
  mongo_data:

networks:
  app-network:
    driver: bridge